### ISSUE TITLE
documentation improvement

### ISSUE THREAD

**Issue by levincode** [Saxboyy/Run-Flatpak-Windows11#1]
Thank you very much, your guide helped me a lot.

I had some problems installing the flatpak, I leave you other sources that helped me:

- a more detailed guide to [setup Xming](https://www.uwyo.edu/data-science/resources/knowledge-base/x11-with-windows-subsystem-for-linux.html)
- and for those who don't know like me. add the `sudo` to the command:
```sh
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
```

**Comment by AbelFalcon** [comment]
Thank you very much. I will update the documentation!
